// DIGIT API endpoint paths — single source of truth
export const ENDPOINTS = {
  AUTH: '/user/oauth/token',
  USER_SEARCH: '/user/_search',
  USER_CREATE: '/user/users/_createnovalidate',
  USER_UPDATE: '/user/users/_updatenovalidate',
  MDMS_SEARCH: '/mdms-v2/v2/_search',
  MDMS_CREATE: '/mdms-v2/v2/_create',
  MDMS_UPDATE: '/mdms-v2/v2/_update',
  MDMS_SCHEMA_CREATE: '/mdms-v2/schema/v1/_create',
  MDMS_SCHEMA_SEARCH: '/mdms-v2/schema/v1/_search',
  BOUNDARY_SEARCH: '/boundary-service/boundary/_search',
  BOUNDARY_CREATE: '/boundary-service/boundary/_create',
  BOUNDARY_HIERARCHY_SEARCH: '/boundary-service/boundary-hierarchy-definition/_search',
  BOUNDARY_HIERARCHY_CREATE: '/boundary-service/boundary-hierarchy-definition/_create',
  BOUNDARY_RELATIONSHIP_CREATE: '/boundary-service/boundary-relationships/_create',
  BOUNDARY_RELATIONSHIP_SEARCH: '/boundary-service/boundary-relationships/_search',
  BOUNDARY_UPDATE: '/boundary-service/boundary/_update',
  BOUNDARY_DELETE: '/boundary-service/boundary/_delete',
  BOUNDARY_RELATIONSHIP_UPDATE: '/boundary-service/boundary-relationships/_update',
  BOUNDARY_RELATIONSHIP_DELETE: '/boundary-service/boundary-relationships/_delete',
  HRMS_EMPLOYEES_SEARCH: '/egov-hrms/employees/_search',
  HRMS_EMPLOYEES_CREATE: '/egov-hrms/employees/_create',
  HRMS_EMPLOYEES_UPDATE: '/egov-hrms/employees/_update',
  LOCALIZATION_SEARCH: '/localization/messages/v1/_search',
  LOCALIZATION_UPSERT: '/localization/messages/v1/_upsert',
  LOCALIZATION_DELETE: '/localization/messages/v1/_delete',
  PGR_CREATE: '/pgr-services/v2/request/_create',
  PGR_SEARCH: '/pgr-services/v2/request/_search',
  PGR_UPDATE: '/pgr-services/v2/request/_update',
  WORKFLOW_BUSINESS_SERVICE_SEARCH: '/egov-workflow-v2/egov-wf/businessservice/_search',
  WORKFLOW_BUSINESS_SERVICE_CREATE: '/egov-workflow-v2/egov-wf/businessservice/_create',
  WORKFLOW_PROCESS_SEARCH: '/egov-workflow-v2/egov-wf/process/_search',
  FILESTORE_UPLOAD: '/filestore/v1/files',
  FILESTORE_URL: '/filestore/v1/files/url',
  ACCESS_ROLES_SEARCH: '/access/v1/roles/_search',
  ACCESS_ACTIONS_SEARCH: '/access/v1/actions/_search',
  IDGEN_GENERATE: '/egov-idgen/id/_generate',
  LOCATION_BOUNDARY_SEARCH: '/egov-location/location/v11/boundarys/_search',

  ENC_ENCRYPT: '/egov-enc-service/crypto/v1/_encrypt',
  ENC_DECRYPT: '/egov-enc-service/crypto/v1/_decrypt',
  BNDRY_MGMT_PROCESS: '/egov-bndry-mgmnt/v1/_process',
  BNDRY_MGMT_GENERATE: '/egov-bndry-mgmnt/v1/_generate',
  BNDRY_MGMT_PROCESS_SEARCH: '/egov-bndry-mgmnt/v1/_process-search',
  BNDRY_MGMT_GENERATE_SEARCH: '/egov-bndry-mgmnt/v1/_generate-search',
  INBOX_V2_SEARCH: '/inbox/v2/_search',
} as const;

export const OAUTH_CONFIG = {
  clientId: 'egov-user-client',
  clientSecret: '',
  grantType: 'password',
  scope: 'read',
} as const;
